name: Deploy da Lambda

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Configure Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Build
        run: |
          mvn clean package
          zip -r terraform/lambda.zip target/*.jar

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Apply Terraform
        run: |
          cd terraform/
          terraform init
          terraform apply -auto-approve
